### ISSUE TITLE
Add META: Metador on SMARTBCH

### ISSUE THREAD

**Issue by Metador-SMARTBCH** [mistswapdex/default-token-list#32]
- [x] I understand that token listing is not required to use the MISTswap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the MIST default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network:
Token Address (checkSum): 
0x7e56D225f69A5b0D1C2FC47673A5c41328fC82e0
Token Name (from contract): METADOR
Token Decimals (from contract): 18
Token Symbol (from contract):  META
MISTswap V2 Pair Address of Token: https://app.mistswap.fi/swap?outputCurrency=0x7e56d225f69a5b0d1c2fc47673a5c41328fc82e0

Link to mistswapdex/assets PR: https://github.com/mistswapdex/assets/issues/39
Link to the official homepage of token: https://smetador.space
Link to CoinMarketCap or CoinGecko page of token:
Link to official Twitter account: https://twitter.com/Metador_SBCH

**Comment by kasumi-1** [comment]
Please add sufficient liquidity, thanks.

**Comment by Metador-SMARTBCH** [comment]
Hello! Minimum liquidity needed please. It's still a new project with $5k+ total volume on mistswap.

**Comment by kasumi-1** [comment]
Anything under $3k or so will not register with our analytics.

**Comment by GiverofMemory** [comment]
> Anything under $3k or so will not register with our analytics.

Hello, $3k just to get listed seems steep.  Even on solana the top swap only requires a 5 sol fee to get listed.  It is great there is no fee here but 3k of liquidity is even tougher to achieve than a fee.  Please advise.

**Comment by kasumi-1** [comment]
Added in e8356a924f3f1bb485d950586c796580330668b1 - thanks
